version: '2'
services:
  serverless-node:
    build:
      context: ./
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - .:/app
      - ~/.aws/:/root/.aws
      - ~/.gcloud/:/root/.gcloud
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_PROFILE
      - AWS_SESSION_TOKEN
      - AWS_SECURITY_TOKEN
  aws-clojure-gradle:
    image: java:8
    volumes:
      - ./tmp/serverless-integration-test-aws-clojure-gradle:/app
  aws-clojurescript-gradle:
    image: pgoudreau/docker-maven-node
    volumes:
      - ./tmp/serverless-integration-test-aws-clojurescript-gradle:/app
  aws-nodejs:
    image: node:5.11.1
    volumes:
      - ./tmp/serverless-integration-test-aws-nodejs:/app
  aws-python:
    image: python:2.7
    volumes:
      - ./tmp/serverless-integration-test-aws-python:/app
  aws-python3:
    image: python:3.7
    volumes:
      - ./tmp/serverless-integration-test-aws-python3:/app
  aws-java-maven:
    image: maven:3-jdk-8
    volumes:
      - ./tmp/serverless-integration-test-aws-java-maven:/app
  aws-java-gradle:
    image: java:8
    volumes:
      - ./tmp/serverless-integration-test-aws-java-gradle:/app
  aws-kotlin-jvm-maven:
    image: maven:3-jdk-8
    volumes:
      - ./tmp/serverless-integration-test-aws-kotlin-jvm-maven:/app
  aws-kotlin-jvm-gradle:
    image: gradle:4.2-jdk8
    volumes:
      - ./tmp/serverless-integration-test-aws-kotlin-jvm-gradle:/app
  aws-kotlin-nodejs-gradle:
    image: pgoudreau/docker-maven-node
    volumes:
      - ./tmp/serverless-integration-test-aws-kotlin-nodejs-gradle:/app
  aws-groovy-gradle:
    image: java:8
    volumes:
      - ./tmp/serverless-integration-test-aws-groovy-gradle:/app
  aws-scala-sbt:
    image: hseeberger/scala-sbt:8u222_1.3.2_2.13.1
    volumes:
      - ./tmp/serverless-integration-test-aws-scala-sbt:/app
  aws-csharp:
    image: microsoft/dotnet:2.0-sdk
    volumes:
      - ./tmp/serverless-integration-test-aws-csharp:/app
  aws-fsharp:
    image: microsoft/dotnet:2.0-sdk
    volumes:
      - ./tmp/serverless-integration-test-aws-fsharp:/app
  aws-go:
    image: golang:1.9
    volumes:
      - ./tmp/serverless-integration-test-aws-go:/app
      - ./tmp/serverless-integration-test-aws-go:/go/src/app
  aws-go-dep:
    image: yunspace/golang:1.9
    volumes:
      - ./tmp/serverless-integration-test-aws-go-dep:/app
      - ./tmp/serverless-integration-test-aws-go-dep:/go/src/app
  aws-go-mod:
    image: golang:1.11
    volumes:
      - ./tmp/serverless-integration-test-aws-go-mod:/app
      - ./tmp/serverless-integration-test-aws-go-mod:/go/src/app
  aws-nodejs-typescript:
    image: node:6.10.3
    volumes:
      - ./tmp/serverless-integration-test-aws-nodejs-typescript:/app
  aws-alexa-typescript:
    image: node:6.10.3
    volumes:
      - ./tmp/serverless-integration-test-aws-alexa-typescript:/app
  aws-nodejs-ecma-script:
    image: node:6.10.3
    volumes:
      - ./tmp/serverless-integration-test-aws-nodejs-ecma-script:/app
  google-nodejs:
    image: node:6.9.1
    volumes:
      - ./tmp/serverless-integration-test-google-nodejs:/app
  google-go:
    image: golang:1.11
    volumes:
      - ./tmp/serverless-integration-test-google-go:/app
      - ./tmp/serverless-integration-test-google-go:/go/src/app
  spotinst-nodejs:
    image: node:4.8
    volumes:
      - ./tmp/serverless-integration-test-spotinst-nodejs:/app
  spotinst-python:
    image: python2.7
    volumes:
      - ./tmp/serverless-integration-test-spotinst-python:/app
  spotinst-ruby:
    image: ruby2.4.1
    volumes:
      - ./tmp/serverless-integration-test-spotinst-ruby:/app
  spotinst-java8:
    image: maven:3-jdk-8
    volumes:
      - ./tmp/serverless-integration-test-spotinst-java8:/app
  twilio-nodejs:
    image: node:8.16.0
    volumes:
      - ./tmp/serverless-integration-test-twilio-nodejs:/app
  aliyun-nodejs:
    image: node:8
    volumes:
      - ./tmp/serverless-integration-test-aliyun-nodejs:/app
