name: "CI: Binary Installer"

permissions:
  contents: read

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflows/ci-binary-installer.yml'
      - 'binary-installer/**'

defaults:
  run:
    working-directory: ./binary-installer

jobs:
  test-binary-installer:
    name: "Test: Binary Installer"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Code"
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: "Setup: Go"
        uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
        with:
          go-version: '>=1.25'
          cache-dependency-path: binary-installer/go.sum
      - name: "Test: Unit"
        run: make test
      - name: "Build: Production"
        run: make build-prod
