name: 'CI: Binary Installer'

permissions:
  contents: read

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    paths:
      - '.github/workflows/ci-binary-installer.yml'
      - 'binary-installer/**'

defaults:
  run:
    working-directory: ./binary-installer

jobs:
  test-binary-installer:
    name: 'Test: Binary Installer'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Code'
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: 'Setup: Go'
        uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
        with:
          go-version: '>=1.25'
          cache-dependency-path: binary-installer/go.sum
      - name: 'Test: Unit'
        run: make test
      - name: 'Build: Production'
        run: make build-prod
