name: 'CI: Engine'

permissions:
  contents: read

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    paths:
      - '.github/workflows/ci-engine.yml'
      - 'packages/engine/**'

jobs:
  test-engine:
    name: 'Test: Engine'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout Code'
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: 'Setup: Node.js'
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version: 24.x
          cache: npm

      - name: 'Install: Dependencies'
        run: npm ci

      - name: 'Test: Unit'
        working-directory: packages/engine
        run: npm test
