name: Publish
on:
  push:
    branches: [package]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PACKAGE_DEPLOYMENT_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          registry-url: "https://npm.pkg.github.com"
          scope: "@apraamcos"
      - name: Setup Git Configs
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
      - name: Install
        run: |
          npm set @apraamcos:registry https://npm.pkg.github.com
          npm set //npm.pkg.github.com/:_authToken ${{ secrets.PACKAGE_DEPLOYMENT_TOKEN }}
          npm ci
      - name: Increase version number
        run: npm version patch -m "[skip ci] Bump version to %s"
      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Push
        run: |
          git push
          git push --tags
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
