name: 'Release: Binary Installer'

permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch:

defaults:
  run:
    working-directory: ./binary-installer

jobs:
  release-installer-binary:
    name: 'Release: Binary Installer'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Code'
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: 'Setup: Go'
        uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
        with:
          go-version: '>=1.25'
          cache-dependency-path: binary-installer/go.sum
      - name: 'Setup: AWS Credentials'
        uses: aws-actions/configure-aws-credentials@8df5847569e6427dd6c4fb1cf565c83acfa8afa7 # v6.0.0
        with:
          role-to-assume: arn:aws:iam::802587217904:role/GithubActionsDeploymentRole
          aws-region: us-east-1
      - name: 'Test: Unit'
        run: make test
      - name: 'Build: Production'
        run: make build-prod
      - name: 'Release: Install Script'
        run: |
          aws s3 cp ./install.sh s3://install.serverless.com/install.sh
      - name: 'Release: Binaries'
        run: |
          aws s3 cp --recursive ./dist/prod s3://install.serverless.com/installer-builds/
      - name: 'Release: Invalidate Cache'
        run: |
          aws cloudfront create-invalidation --distribution-id E3OEL4OJF1G5FG --paths "/install.sh" "/installer-builds/*"
